version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - '80:80'

  fluent-bit:
    image: fluent/fluent-bit:1.9
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
      - ./fluent-bit/log:/fluent-bit/log
    ports:
      - '24224:24224'
